# Generated by Django 5.1.7 on 2025-05-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lark_open_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
