# Generated by Django 5.1.7 on 2025-05-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detachment',
            name='init',
            field=models.BooleanField(default=False),
        ),
    ]
