"""
Django settings for THUPracticeOnline_backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$xfjrc7m!=*vj!6ft48-%7e*5io^il0hllvu^l=qh%^4f=-fiw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['.spring25a.secoder.net']


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'users.apps.UsersConfig', 
    'detachments.apps.DetachmentsConfig',
    'notices.apps.NoticesConfig',
    'files.apps.FilesConfig',
    'connection_lists.apps.ConnectionListsConfig',
    'approvals.apps.ApprovalsConfig',
    'handbooks.apps.HandbooksConfig',
    'logs.apps.LogsConfig',
    'votes.apps.VotesConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'POST',
    'GET',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    # 'content-disposition',
    # 'Content-Disposition',
]   
 
CORS_EXPOSE_HEADERS = ['Content-Disposition']

CORS_ALLOWED_ORIGINS = [
    'https://THUPracticeOnline-backend-develop-THUPracticeOnline.app.spring25a.secoder.net',
    'https://THUPracticeOnline-backend-THUPracticeOnline.app.spring25a.secoder.net',
    'https://THUPracticeOnline-frontend-THUPracticeOnline.app.spring25a.secoder.net',
    'https://THUPracticeOnline-frontend-develop-THUPracticeOnline.app.spring25a.secoder.net',
    'https://thupracticeonline-frontend-thupracticeonline.app.spring25a.secoder.net',
    'https://thupracticeonline-backend-thupracticeonline.app.spring25a.secoder.net',
    'https://thupracticeonline-backend-develop-thupracticeonline.app.spring25a.secoder.net',
    'https://thupracticeonline-frontend-develop-thupracticeonline.app.spring25a.secoder.net',
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://\w+\.app\.spring25a\.secoder\.net$'
]

ROOT_URLCONF = 'THUPracticeOnline_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'THUPracticeOnline_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

ENVIRONMENT = os.getenv('DJANGO_ENV', 'development')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'prod_database' if ENVIRONMENT == 'production' else 'dev_database',
        'USER': 'root',
        'PASSWORD': 'THUPracticeOnline',
        'HOST': 'THUPracticeOnline-db.THUPracticeOnline.secoder.local',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.CookieJWTAuthentication',
    ],
    'EXCEPTION_HANDLER': 'THUPracticeOnline_backend.exception_handler.custom_exception_handler',
}

# JWT 配置（可选）
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

AUTH_USER_MODEL = 'users.CustomUser'

#邮件发送配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'THUPracticeOnline@163.com'
EMAIL_HOST_PASSWORD = 'HUpyhkBpA4hXCbLq'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/1')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'TIMEOUT': 600,
    }
}

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#         'LOCATION': 'unique-snowflake',  # 可自定义的标识符
#     }
# }

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# 飞书API配置
LARK_CONFIG = {
    'APP_ID': 'cli_a8934377ba18d013',
    'APP_SECRET': 'l0Mep1uf7lv5MFqS07mmJbZuVrJJE7tV',
}