# Generated by Django 5.1.7 on 2025-04-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detachment_name', models.CharField(max_length=100)),
                ('leader', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('enterprise', models.CharField(max_length=1000)),
                ('government', models.CharField(max_length=1000)),
                ('venue', models.CharField(max_length=1000)),
            ],
        ),
    ]
