# Generated by Django 5.1.7 on 2025-05-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_lists', '0002_alter_connectionlistmodel_detachment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionlistmodel',
            name='detachment_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
