# Generated by Django 5.1.7 on 2025-05-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_lists', '0003_alter_connectionlistmodel_detachment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('mime_type', models.CharField(default='', max_length=100)),
                ('filename', models.CharField(max_length=200)),
            ],
        ),
    ]
