# Generated by Django 5.1.7 on 2025-05-13 23:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detachments', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2025, 5, 13))),
                ('content', models.CharField(max_length=200)),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detachments.detachment')),
            ],
        ),
    ]
