# Generated by Django 5.1.7 on 2025-05-14 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 14)),
        ),
    ]
