# Generated by Django 5.1.7 on 2025-05-21 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_logmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 21)),
        ),
    ]
