# Generated by Django 5.1.7 on 2025-05-20 23:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detachments', '0002_detachment_init'),
        ('logs', '0002_alter_logmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='detachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_for_detachment', to='detachments.detachment'),
        ),
    ]
