# Generated by Django 5.1.7 on 2025-05-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_logmodel_date'),
        ('logs', '0003_alter_logmodel_date_alter_logmodel_detachment'),
    ]

    operations = [
    ]
