# Generated by Django 5.1.7 on 2025-05-22 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_merge_20250521_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
